### ISSUE TITLE
Django Suit + Filer + Custom User Model fails when Suit initializes in DEBUG

### ISSUE THREAD

**Issue by chris-erickson** [django-cms/django-filer#390]
Running my site in debug mode, everything works great.  Set `DEBUG=False`, and the problem happens.  I'm using auth-tools which essentially follows the Django guide on Custom User models.

Suit seems to initialize filer, from `config.py` via 

``` python
if 'filer' in settings.INSTALLED_APPS:
    setup_filer()
```

https://github.com/darklow/django-suit/blob/develop/suit/config.py#L74

This is what is in the uwsgi logs:

```
Traceback (most recent call last):
  File "/var/www/venvs/somesite.com/local/lib/python2.7/site-packages/dj_static.py", line 59, in __call__
    return self.application(environ, start_response)
  File "/var/www/venvs/somesite.com/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
    self.load_middleware()
  File "/var/www/venvs/somesite.com/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 49, in load_middleware
    mw_instance = mw_class()
  File "/var/www/venvs/somesite.com/local/lib/python2.7/site-packages/django/middleware/locale.py", line 24, in __init__
    for url_pattern in get_resolver(None).url_patterns:
  File "/var/www/venvs/somesite.com/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 346, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/var/www/venvs/somesite.com/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 341, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/var/www/venvs/somesite.com/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "./sitename/urls.py", line 7, in <module>
    admin.autodiscover()
  File "/var/www/venvs/somesite.com/local/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 29, in autodiscover
    import_module('%s.admin' % app)
  File "/var/www/venvs/somesite.com/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/var/www/venvs/somesite.com/local/lib/python2.7/site-packages/suit/admin.py", line 2, in <module>
    import suit.config
  File "/var/www/venvs/somesite.com/local/lib/python2.7/site-packages/suit/config.py", line 75, in <module>
    setup_filer()
  File "/var/www/venvs/somesite.com/local/lib/python2.7/site-packages/suit/config.py", line 61, in setup_filer
    from filer.admin.imageadmin import ImageAdminForm
  File "/var/www/venvs/somesite.com/local/lib/python2.7/site-packages/filer/admin/__init__.py", line 4, in <module>
    from filer.admin.fileadmin import FileAdmin
  File "/var/www/venvs/somesite.com/local/lib/python2.7/site-packages/filer/admin/fileadmin.py", line 10, in <module>
    from filer.views import (popup_param, selectfolder_param, popup_status,
  File "/var/www/venvs/somesite.com/local/lib/python2.7/site-packages/filer/views.py", line 120, in <module>
    class UploadFileForm(forms.ModelForm):
  File "/var/www/venvs/somesite.com/local/lib/python2.7/site-packages/django/forms/models.py", line 282, in __new__
    opts.help_texts, opts.error_messages)
  File "/var/www/venvs/somesite.com/local/lib/python2.7/site-packages/django/forms/models.py", line 201, in fields_for_model
    formfield = f.formfield(**kwargs)
  File "/var/www/venvs/somesite.com/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 1258, in formfield
    (self.name, self.rel.to))
ValueError: Cannot create form field for 'owner' yet, because its related model 'authtools.User' has not been loaded yet
```

Switch back into DEBUG, restart, and everything works as expected.

Filer @ 0.9.5
Suit @ 0.2.6
Django @ 1.6.2

**Comment by bashu** [comment]
4 years later and the same problem...
