### ISSUE TITLE
Compatibility with Django 1.10.1 (Migration needed)

### ISSUE THREAD

**Issue by levivm** [django-cms/django-filer#929]
I need to use Django 1.10.1. But when I try to run migrate command, I'm getting this:

```

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/Levi/.virtualenvs/ungleich/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/Users/Levi/.virtualenvs/ungleich/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/Levi/.virtualenvs/ungleich/lib/python3.5/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/Levi/.virtualenvs/ungleich/lib/python3.5/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/Users/Levi/.virtualenvs/ungleich/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 83, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/Users/Levi/.virtualenvs/ungleich/lib/python3.5/site-packages/django/db/migrations/executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/Users/Levi/.virtualenvs/ungleich/lib/python3.5/site-packages/django/db/migrations/loader.py", line 52, in __init__
    self.build_graph()
  File "/Users/Levi/.virtualenvs/ungleich/lib/python3.5/site-packages/django/db/migrations/loader.py", line 268, in build_graph
    raise exc
  File "/Users/Levi/.virtualenvs/ungleich/lib/python3.5/site-packages/django/db/migrations/loader.py", line 238, in build_graph
    self.graph.validate_consistency()
  File "/Users/Levi/.virtualenvs/ungleich/lib/python3.5/site-packages/django/db/migrations/graph.py", line 261, in validate_consistency
    [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
  File "/Users/Levi/.virtualenvs/ungleich/lib/python3.5/site-packages/django/db/migrations/graph.py", line 261, in <listcomp>
    [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
  File "/Users/Levi/.virtualenvs/ungleich/lib/python3.5/site-packages/django/db/migrations/graph.py", line 104, in raise_error
    raise NodeNotFoundError(self.error_message, self.key, origin=self.origin)
django.db.migrations.exceptions.NodeNotFoundError: Migration ungleich.0001_initial dependencies reference nonexistent parent node ('filer', '0008_merge_20161027_0507')
```

**Comment by yakky** [comment]
@levivm are you sure you did not run a ``makemigrations --merge`` when creating ungleich application? ``filer.0008_merge_20161027_0507`` does not exists in the repository, it looks like a locally created migration

**Comment by pawelmarkowski** [comment]
Next compatibility issue is caused by django-polymorphic. Current pip version of this package is 0.8.1 that raises the error:

../polymorphic/base.py line 148, in get_inherited_managers
    if manager._inherited:
AttributeError: 'Manager' object has no attribute '_inherited

Therefore I had to install django-polymorphic==1.0.2 from https://github.com/django-polymorphic/django-polymorphic/archive/master.zip 

You can update requirements scheme.
